desc "Build for testing"
lane :build_for_testing do 
  scan(
    derived_data_path: "DerivedData",
    build_for_testing: true,
    clean: true
  )
end

desc "Testing w/o build"
lane :testing do
  run_tests(
   derived_data_path: "DerivedData",
   test_without_building: true
  )
end

desc "Send notification to discord"
lane :discord_notification do

  webhook_url = ENV['DISCORD_WEBHOOK_URL']

  discord_notifier(
    webhook_url:webhook_url,
    title: "SuperCI",
    description: "Success build and test",
  )
end

desc "Build, test and notify"
lane :build_and_test do
  build_for_testing
  testing
  discord_notification
  puts 'SUCCESS KEK!'
end


